[build]
  command = "npm run build"
  publish = ".next"
  NODE_OPTIONS = "â€“max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/scripts/zulip-notification"
